class Product {
  int? id; // will be auto-generated by the database
  String name; // product name
  int quantity; // how many in stock
  double price; // how much it costs
  String? imagePath; // file path to the product image (optional)

  Product({
    this.id,
    required this.name,
    required this.quantity,
    required this.price,
    this.imagePath,
  });

  // Convert Product -> Map<String, dynamic> for inserting into SQLite
  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{
      'name': name,
      'quantity': quantity,
      'price': price,
      'imagePath': imagePath,
    };

    // The ID only exists after insert
    if (id != null) {
      map['id'] = id;
    }

    return map;
  }

  // Convert Map<String, dynamic> -> Product for reading from SQLite
  factory Product.fromMap(Map<String, dynamic> map) {
    return Product(
      id: map['id'] as int?,
      name: map['name'] as String,
      quantity: map['quantity'] as int,
      price: (map['price'] as num).toDouble(),
      imagePath: map['imagePath'] as String?,
    );
  }
}
